UIREQ-943 create Jest/RTL test for NoteCreateRoute.js
folio-org/ui-requests pull request #1039
Opened 2023-05-12 08:33 UTC by cchitneedi

Refs: 
UIREQ-943 create Jest/RTL test for NoteCreateRoute.js

URL: https://issues.folio.org/browse/UIREQ-943

2023-05-12 13:53 UTC, artem-blazhko requested changes
Could add appropriate changes to CHANGELOG.md file?
Could you test redirect functionality in this file?

2023-05-12 13:53 UTC, artem-blazhko commented on src/routes/NoteCreateRoute.test.js
> +    expect(screen.getByText('NoteCreatePage'));
What do you expect in this test?

2023-05-12 13:53 UTC, artem-blazhko commented on src/routes/NoteCreateRoute.test.js
> +const renderNoteCreateRoute = (data1, data2) => render(
Could you use a bit more specific names and avoid using "data1", "data2"?

2023-05-12 13:53 UTC, artem-blazhko commented on src/routes/NoteCreateRoute.test.js
> +  'listen': () => {},
I do not see any reason to wrap object properties in quotation marks.
Could you remove it?

2023-05-12 13:53 UTC, artem-blazhko commented on src/routes/NoteCreateRoute.test.js
> +  NoteCreatePage: (props) => <div><span>NoteCreatePage</span><button type="button" onClick={() => props.renderReferredRecord()}>renderReferredRecord</button></div>,
Could you add mock to 'ui-requests\test\jest\__mock__\stripesSmartComponents.mock.js'?

2023-05-16 09:44 UTC, cchitneedi commented
Hi @artem-blazhko ,
Changes have been done as mentioned.

Thanks and Regards,
Charan

2023-05-16 13:29 UTC, artem-blazhko requested changes

2023-05-16 13:29 UTC, artem-blazhko commented on CHANGELOG.md
> +* Added NoteCreatePage function to 'ui-requests\test\jest_mock_\stripesSmartComponents.mock.js'
Could you add only:
`Create Jest/RTL test for NoteCreateRoute.js. Refs: UIREQ-943.`
at the end of the "IN PROGRESS" section?

2023-05-17 09:18 UTC, cchitneedi commented on src/routes/NoteCreateRoute.test.js
> +    userEvent.click(screen.getByRole('button', { name: 'renderReferredRecord' }));
Changes Done

2023-05-24 09:57 UTC, artem-blazhko approved these changes

2023-05-24 12:24 UTC, merged