UIREQ-937 create JEST/RTL test cases for RequestsFilters.js
folio-org/ui-requests pull request #1044
Opened 2023-05-17 11:25 UTC by ssandupatla

UIREQ-937 create JEST/RTL test cases for RequestsFilters.js
URL: https://issues.folio.org/browse/UIREQ-937

2023-05-24 09:23 UTC, artem-blazhko requested changes
Could you add changes to changelog file?
Could you check that `RequestLevelFilter` is rendered/not rendered?
 Could you check that all necessary `MultiSelectionFilter` rendered?

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +import React from 'react';
It is not necessary to import.

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +}));
We have separate files with mocks - `test/jest/__mock__`.
You can add your mocks there if those mocks do not exist yet.

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +    userEvent.click(requestTypeButton);
What is the reason to trigger `click` event here?
Is it necessary only for increasing code coverage?

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +    userEvent.click(requestStatusButton);
What is the reason to trigger `click` event here?
Is it necessary only for increasing code coverage?

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +    userEvent.click(tagsButton);
What is the reason to trigger `click` event here?
Is it necessary only for increasing code coverage?

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +  });
I see that the first three tests have the same render approach.
Could you add `beforeEach` statement and call `render(<RequestsFilters {...props} />)` inside for first three tests?

2023-05-24 09:23 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +  it('render the accordion pickup service points', () => {
Could you mock `PickupServicePointFilter` and check that it is rendered. There is no sence to check rendering of inner components of `PickupServicePointFilter`. `PickupServicePointFilter` has or will have in future its own tests.

2023-06-06 13:45 UTC, artem-blazhko requested changes
Could you check the rendering of `CheckboxFilter`?
From the code perspective, I see that `CheckboxFilter` rendered twice. Would be great to check each render.

2023-06-06 13:45 UTC, artem-blazhko commented on src/components/RequestsFilters/RequestsFilters.test.js
> +  });
Could you create 3 separate tests (1 for each "click" action) and check that `onClear` was called with correct argument?

2023-06-06 13:45 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +      {/* <div>{<button type="button" onClick={() => onClearFilter()} data-testid={`clear-${name}`}>Clear</button> : null}</div> */}
do we need that comment?

2023-06-08 14:33 UTC, Dmitriy-Litvinenko requested changes

2023-06-12 09:48 UTC, Dmitriy-Litvinenko reviewed
Could you please fix feedbacks?

2023-06-26 09:17 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-03 09:11 UTC, artem-blazhko requested changes

2023-07-03 09:11 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  ConfirmationModal: jest.fn(({ heading, confirmLabel, cancelLabel, onConfirm, onCancel }) => (
I do not see the usage of that component. Do we really need to change the mock?

2023-07-03 09:11 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  ErrorModal: jest.fn(({ label, content, buttonLabel, onClose }) => (
I do not see the usage of that component. Do we really need to change the mock?

2023-07-03 09:11 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> -      <div>MultiColumnList</div>
I do not see the usage of that component. Do we really need to change the mock?

2023-07-03 09:11 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> -  }) => {
Could you clarify why do we need to change that mock?

2023-07-03 09:11 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  Select: ({ name, label, onChange, required, children, value }) => {
Could you clarify why we need to change that mock?

2023-07-12 04:04 UTC, ssandupatla commented on src/components/RequestsFilters/RequestsFilters.test.js
> +)));
We have added the mock functions to the test file because other test cases in this module will fail if added test/__mock__stripesComponents.mock.js

2023-07-12 04:07 UTC, ssandupatla commented on CHANGELOG.md
> +* Create Jest/RTL test for RequestsFilters.js Refs UIREQ-937.
Updated in Changelog.md

2023-08-31 11:33 UTC, Dmitriy-Litvinenko commented
Thank you for yours pull request. We will use it for increase code coverage.

2023-08-31 11:33 UTC, closed without merging