UIREQ-931 create JEST/RTL test cases for ComponentToPrint.js
folio-org/ui-requests pull request #1048
Opened 2023-05-18 10:58 UTC by ssandupatla

UIREQ-931 create JEST/RTL test cases for ComponentToPrint.js
URL: https://issues.folio.org/browse/UIREQ-931

2023-05-24 09:04 UTC, artem-blazhko requested changes
Could you add changes to the changelog file?
Could you separately test methods inside `rules` array?
Could test scenario when `Component` is null (23 line in the ComponentToPrint.js file)?

2023-05-24 09:04 UTC, artem-blazhko commented on src/components/ComponentToPrint/ComponentToPrint.test.js
> +
I am not sure that it is the correct approach.
Test should contain `expect` statement.
Could you remove it?

2023-05-24 09:04 UTC, artem-blazhko commented on src/components/ComponentToPrint/ComponentToPrint.test.js
> +    const barcodeComponent = getByTestId('barcode-component');
Could you follow one approach with constants declaration?
In some places you do not have spaces between constants, in other places you have space.
```suggestion
    const templateFn = jest.fn(() => '<barcode>123456</barcode>');
    const dataSource = {};
    const { getByTestId } = render(<ComponentToPrint templateFn={templateFn} dataSource={dataSource} />);
    const barcodeComponent = getByTestId('barcode-component');
```

2023-06-08 11:42 UTC, Dmitriy-Litvinenko requested changes
Could you please update CHANGELOG.md?

2023-06-12 09:48 UTC, Dmitriy-Litvinenko reviewed
Could you please fix feedbacks?

2023-06-26 09:17 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-11 13:11 UTC, artem-blazhko requested changes
Could you add changes to the changelog file?

2023-07-11 13:11 UTC, artem-blazhko commented on src/components/ComponentToPrint/ComponentToPrint.test.js
> +    parser.parseWithInstructions = originalParseWithInstructions;
Could you add it to the `afterEach` statement?

2023-07-11 13:11 UTC, artem-blazhko commented on src/components/ComponentToPrint/ComponentToPrint.test.js
> +    parser.parseWithInstructions = originalParseWithInstructions;
the same here

2023-07-13 08:37 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-14 12:24 UTC, cchitneedi approved these changes

2023-08-28 12:53 UTC, Dmitriy-Litvinenko approved these changes

2023-08-28 12:56 UTC, artem-blazhko approved these changes

2023-08-28 13:16 UTC, merged