UIREQ-939 JEST/RTL test cases for PickupServicePointFilter
folio-org/ui-requests pull request #1049
Opened 2023-05-19 05:06 UTC by KetineniM

UIREQ-939 JEST/RTL test cases for PickupServicePointFilter
URL: https://issues.folio.org/browse/UIREQ-939

2023-05-19 11:49 UTC, cchitneedi approved these changes

2023-05-24 08:55 UTC, artem-blazhko requested changes
Could you add appropriate changes to changelog file?

2023-05-24 08:55 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +}));
Could you add mocks to appropriate files here if they does not exist yet - `test/jest/__mock__` ?

2023-05-24 08:55 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +      <div><button type="button" onClick={() => onClearFilter()} data-testid={`clear-${name}`}>Clear</button></div>
```suggestion
      <div>
        <button
          type="button"
          onClick={onClearFilter}
          data-testid={`clear-${name}`}
        >Clear</button>
      </div>
```

2023-05-24 08:55 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +    expect(onClear).toHaveBeenCalled();
Could you add two separate tests for each expect?

2023-05-24 08:55 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +  it('should render the component with default props', () => {
The name of the test does not fit test scenario.

2023-06-06 13:49 UTC, artem-blazhko commented on CHANGELOG.md
> +
Could you remove empty line?

2023-06-06 13:51 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +describe('PickupServicePointFilter', () => {
Could you also check that `MultiSelectionFilter` is rendered and called with correct props?

2023-06-06 13:52 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +    expect(onClear).toHaveBeenCalled();
Would be great to check that it was called with correct argument.

2023-06-06 13:54 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  AccordionSet: jest.fn(({ children, onToggle }) => (
I do not see the usage of this component inside `PickupServicePointFilter`. Do we really need to mock it?

2023-06-06 13:54 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  ConfirmationModal: jest.fn(({ heading, confirmLabel, cancelLabel, onConfirm, onCancel }) => (
I do not see the usage of this component inside `PickupServicePointFilter`. Do we really need to mock it?

2023-06-06 13:54 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  ErrorModal: jest.fn(({ label, content, buttonLabel, onClose }) => (
I do not see the usage of this component inside `PickupServicePointFilter`. Do we really need to mock it?

2023-06-06 13:54 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
> +  Select: ({ name, label, onChange, required, children, value }) => {
I do not see the usage of this component inside `PickupServicePointFilter`. Do we really need to mock it?

2023-06-06 13:55 UTC, artem-blazhko commented on test/jest/__mock__/stripesSmartComponents.mock.js
> +  ProxyManager: () => (<div data-testid="proxy-manager" />),
I do not see the usage of this component inside `PickupServicePointFilter`. Do we really need to mock it?

2023-06-06 13:55 UTC, artem-blazhko commented on test/jest/__mock__/stripesSmartComponents.mock.js
> +  NoteCreatePage: (props) => {
I do not see the usage of this component inside PickupServicePointFilter. Do we really need to mock it?

2023-06-12 09:49 UTC, Dmitriy-Litvinenko reviewed
Could you please fix feedbacks?

2023-06-23 10:34 UTC, KetineniM commented
> Could you please fix feedbacks?

I have fixed the feedback issues, could you please check and let me know

2023-06-26 09:17 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-06-26 10:41 UTC, KetineniM commented
> Could you please fix feedbacks?

I have made all the possible changes. Please let me know if there is anything else remaining.

2023-07-03 08:31 UTC, artem-blazhko commented on CHANGELOG.md
> +
Could you remove empty line?

2023-07-03 08:44 UTC, artem-blazhko commented on test/jest/__mock__/stripesComponents.mock.js
>      </div>
```suggestion
  Accordion: jest.fn(({ children, label, name, onClearFilter }) => (
    <div data-testid={`accordion-${name}`} >
      {label}
      {children}
      <div>
        <button
          type="button"
          onClick={onClearFilter}
          data-testid={`clear-${name}`}
        >Clear
        </button>
      </div>
    </div>
```

2023-07-03 08:44 UTC, artem-blazhko commented on test/jest/__mock__/stripesSmartComponents.mock.js
> +  NoteCreatePage: (props) => {
I do not see the usage of this component inside PickupServicePointFilter. Do we really need to mock it?

2023-07-03 08:44 UTC, artem-blazhko commented on src/components/RequestsFilters/PickupServicePointFilter/PickupServicePointFilter.test.js
> +    const activeValue = screen.getByText('test');
```suggestion
    const activeValue = screen.getByText(activeValues[0]);
```

2023-07-11 13:19 UTC, artem-blazhko commented on CHANGELOG.md
> +* Create Jest/RTL test for PickupServicePointFilter.js Refs UIREQ-939.
Could you move it to the bottom of the list?

2023-07-12 11:39 UTC, merged