UIREQ-941 JEST/RTL test cases for SortableList
folio-org/ui-requests pull request #1051
Opened 2023-05-19 11:22 UTC by KetineniM

UIREQ-941 JEST/RTL test cases for SortableList
URL: https://issues.folio.org/browse/UIREQ-941

2023-05-19 11:48 UTC, cchitneedi approved these changes

2023-05-24 08:14 UTC, artem-blazhko requested changes
Could you check that MultiColumnList and `provided.placeholder` were rendered?

2023-05-24 08:14 UTC, artem-blazhko commented on CHANGELOG.md
> +* create Jest/RTL test for SortableList.js. Refs UIREQ-941.
```suggestion
* Create Jest/RTL test for SortableList.js. Refs UIREQ-941.
```

2023-05-24 08:14 UTC, artem-blazhko commented on src/components/SortableList/SortableList.test.js
> +describe('renderSortableList', () => {
```suggestion
describe('SortableList', () => {
```

2023-05-25 06:12 UTC, ssandupatla approved these changes

2023-05-26 16:27 UTC, artem-blazhko commented on src/components/SortableList/SortableList.test.js
> +  });
```suggestion
  beforeEach(() => {
    renderSortableList(propsData);
  });

  it('Should render the SortableList component with provided droppableId', () => {
    expect(document.querySelector('[droppableid="droppableId1"]')).toBeInTheDocument();
  });
  
  it('Should render the MultiColumnList', () => {
    expect(screen.getByText('MultiColumnList')).toBeInTheDocument();
  });
  
  it('Should render the Provided Placeholder', () => {
    expect(screen.getByText('Placeholder')).toBeInTheDocument();
  });
```

2023-06-06 13:59 UTC, artem-blazhko approved these changes
Could you change my single comment and then we can merge it?

2023-06-07 18:33 UTC, artem-blazhko approved these changes

2023-06-09 06:03 UTC, merged