UIREQ-940 create JEST/RTL test cases for DraggableRow.js
folio-org/ui-requests pull request #1058
Opened 2023-05-25 15:00 UTC by ssandupatla

UIREQ-940 create JEST/RTL test cases for DraggableRow.js
URL: https://issues.folio.org/browse/UIREQ-940

2023-05-26 06:48 UTC, cchitneedi approved these changes

2023-06-23 11:15 UTC, Dmitriy-Litvinenko requested changes

2023-06-23 11:15 UTC, Dmitriy-Litvinenko commented on src/components/SortableList/DraggableRow.test.js
> +  };
Could you please add 
 ```
 const props = {
    cells,
    provided,
    snapshot: {
      isDragging: false,
    },
    rowClass: 'row-class',
    rowIndex: 1,
    rowProps,
  };
```
  ?

2023-06-23 11:15 UTC, Dmitriy-Litvinenko commented on src/components/SortableList/DraggableRow.test.js
> +      <DraggableRow
Could you please change to `<DraggableRow {...props} />`?

2023-06-23 11:15 UTC, Dmitriy-Litvinenko commented on src/components/SortableList/DraggableRow.test.js
> +      <DraggableRow
Could you please change to `<DraggableRow {...props} />`?

2023-06-23 11:15 UTC, Dmitriy-Litvinenko commented on src/components/SortableList/DraggableRow.test.js
> +      <DraggableRow
Could you please change to 
```
    const draggableProps = {
      ...props,
      snapshot: {
        isDragging: true,
      },
    };
```
`<DraggableRow {...draggableProps} />`?

2023-06-26 09:17 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-12 11:03 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-13 13:59 UTC, ssandupatla commented on src/components/SortableList/DraggableRow.test.js
> +  test('DraggableRow using portal', () => {
@Dmitriy-Litvinenko - Changes done as per your suggestion.

2023-08-28 11:07 UTC, Dmitriy-Litvinenko approved these changes

2023-08-28 13:09 UTC, merged