UIREQ-946 JEST/RTL test cases for RequestQueueRoute
folio-org/ui-requests pull request #1060
Opened 2023-05-26 04:41 UTC by KetineniM

UIREQ-946 JEST/RTL test cases for RequestQueueRoute
URL: https://issues.folio.org/browse/UIREQ-946

2023-05-26 06:29 UTC, cchitneedi approved these changes

2023-05-26 16:24 UTC, artem-blazhko requested changes

2023-05-26 16:24 UTC, artem-blazhko commented on src/routes/RequestQueueRoute.test.js
> +    });
Could you create separate tests for each "expect"?

2023-06-12 09:46 UTC, Dmitriy-Litvinenko reviewed
Could you please fix feedbacks?

2023-06-23 11:56 UTC, artem-blazhko requested changes

2023-06-23 11:56 UTC, artem-blazhko commented on src/routes/RequestQueueRoute.test.js
> +}));
We already have it in `test/jest/__mock__/stripesCore.mock.js` file

2023-06-23 11:56 UTC, artem-blazhko commented on src/routes/RequestQueueRoute.test.js
> +    expect(mockMutator.requests.GET).toHaveBeenCalled();
Seems that it is redundant and it is a part of the next test.

2023-06-23 11:56 UTC, artem-blazhko commented on src/routes/RequestQueueRoute.test.js
> +  it('should call setTlrSettings on mount if configs have loaded', () => {
Name of the test does not fit test body.
In this test you check that `requests.GET` is called after rerender and is not called after mount.

2023-06-26 09:16 UTC, Dmitriy-Litvinenko commented
Could you please fix feedbacks?

2023-07-11 12:31 UTC, artem-blazhko commented on src/routes/RequestQueueRoute.test.js
> +  it('should call setTlrSettings on mount if configs have loaded', () => {
Name of the test does not fit test body.
In this test you check that requests.GET is called after rerender but not after the first render (mount).

2023-07-12 09:33 UTC, Dmitriy-Litvinenko approved these changes

2023-07-12 09:41 UTC, artem-blazhko approved these changes

2023-07-12 09:49 UTC, merged