UI req 990 add dropdown for item service point
folio-org/ui-requests pull request #1108
Opened 2023-09-28 04:37 UTC by rgupta-nla

## Purpose
https://issues.folio.org/browse/UIREQ-989
To populate the drop down the (ServicePoint) code will need to be used, this allows the already existing service point code to be leveraged.

User must have the view request permission. Users: View requests, this should also limit them to their assigned service point/s. (This may need to be updated to suit general open source) This does match the generic permission in snapshot.

## Approach
The request list is filtered in the backend based on the item selected in Primary Service Point name dropdown in the ui.

![image](https://github.com/folio-org/ui-requests/assets/127274721/90c9f2ba-288d-468c-9abd-88e4c0c81267)

## Refs

## Screenshots

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-10-02 23:44 UTC, fcrimmins commented on src/constants.js
> +  EffLocation_SERVICE_POINT: 'effectiveLocationPrimaryServicePoint',
Should this be an all-caps constant name to match the other types?

2023-10-02 23:45 UTC, fcrimmins approved these changes

2023-10-05 14:22 UTC, Dmitriy-Litvinenko requested changes

2023-10-05 14:22 UTC, Dmitriy-Litvinenko commented on src/components/RequestsFilters/EffectiveLocationServicePointFilter/EffectiveLocationServicePointFilter.js
> +      label="Effective Location Primary Service Point Name"
Could you please move label text to translation?
Could you please clarify label (current text not consistency)?

2023-10-05 14:22 UTC, Dmitriy-Litvinenko commented on src/components/RequestsFilters/EffectiveLocationServicePointFilter/EffectiveLocationServicePointFilter.test.js
> +import '__mock__';
Could you  please remove?

2023-10-05 14:22 UTC, Dmitriy-Litvinenko commented on translations/ui-requests/en.json
> +  "requests.itemEffectiveLocationPrimaryServicePointName": "Effective Location Primary Service Point Name",
Could you please clarify text (current text not consistency)?

2023-10-05 14:24 UTC, Dmitriy-Litvinenko commented
Could you please resolve conflict and fix feedback?

2024-04-30 11:38 UTC, Dmitriy-Litvinenko commented
We close current pull request. Pull request long time without any updates, need rebase and etc. If needed can be reopened.

2024-04-30 11:38 UTC, closed without merging