UIREQ-747: Add success toast to duplicated Requests
folio-org/ui-requests pull request #880
Opened 2022-03-10 14:28 UTC by pavelspichonak

## Purpose
Add success toast to duplicated Requests

## Refs
https://issues.folio.org/browse/UIREQ-747

2022-03-14 06:22 UTC, Stanislau-Snapok approved these changes

2022-03-14 14:54 UTC, mkuklis approved these changes

2022-03-14 20:17 UTC, zburke requested changes
lint that `:` 🙄 and then this looks great!

2022-03-15 06:23 UTC, Stanislau-Snapok commented
> lint that `:` 🙄 and then this looks great!

Good point! Pavel is on vacation now, so I'll take care about this. Thanks!

2022-03-17 06:43 UTC, merged