UIREQ-883: UI tests replacement with RTL/Jest for src/components/ErrorModal.js
folio-org/ui-requests pull request #999
Opened 2023-02-06 17:28 UTC by s3fs

## Purpose
UI tests replacement with RTL/Jest

## Approach
Tested for appearance, props->content display and an ability to call the close function.

## Refs
https://issues.folio.org/browse/UIREQ-883

## Screenshots

#### TODOS and Open Questions
- [ ] If there's additional functionality that needs to be covered please let me know.

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [x] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-02-06 17:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/ui-requests?pullRequest=999) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/ui-requests?pullRequest=999) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/ui-requests?pullRequest=999) it.</sub>

2023-02-07 10:04 UTC, artem-blazhko commented on src/components/ErrorModal/ErrorModal.test.js
> +  });
I would split each test into 2 tests. One test - one `expect`.

2023-02-07 10:04 UTC, artem-blazhko commented on src/components/ErrorModal/ErrorModal.js
> +const ErrorModal = ({ errorMessage, onClose, label }) => {
```suggestion
const ErrorModal = ({
  errorMessage,
  onClose,
  label,
}) => {
```

2023-02-07 10:13 UTC, s3fs commented on src/components/ErrorModal/ErrorModal.test.js
> +  const renderComponent = ({
Looks better (more readable) with spaces IMO, but I see that your suggestion is preferred in existing code. Will change

2023-02-07 11:01 UTC, artem-blazhko approved these changes

2023-02-08 10:09 UTC, Dmitriy-Litvinenko requested changes

2023-02-08 12:43 UTC, Dmitriy-Litvinenko approved these changes

2023-02-08 12:58 UTC, merged